### ISSUE TITLE
Problème lors de l'authentification discord

### ISSUE THREAD

**Issue by Supertolek** [micuit-cuit/bien-ou-bot#15]
Je me suis connecté à l'aide du `/login`, mais les autres commandes me disent que je ne suis pas connecté.
![Screenshot_2024-06-17-08-54-03-428_com discord-edit](https://github.com/micuit-cuit/bien-ou-bot/assets/105239958/f8ac133e-8000-4c4b-9f9a-f7f1164cc6dd)

**Comment by micuit-cuit** [comment]
je regarde sa

**Comment by micuit-cuit** [comment]
j'ai trouvez le probleme, sa vien de la database
je le fix
